services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: coresphere-hms-app

    ports:
      - "3001:3000"

    env_file:
      - .env

    depends_on:
      - db

    restart: unless-stopped

  db:
    image: postgres:16

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coresphere

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres-data: